version: '2'
services:

    django:
        extends:
            file: common.yml
            service: django
        command: python manage.py runserver 0.0.0.0:8000
        ports:
          - "8000:8000"
        volumes:
          - ./code:/code
        environment:
          - DEPLOY_ENV=development
        depends_on:
          - postgres

    postgres:
        image: postgres
        container_name: postgres